en = {
	"1": "Start file manager?  [y/n]",
	"2": "starting Explorer",
	"3": "Choose option",
	"4": "Display information about the folder",
	"5": "Display information about the system",
	"6": "Run calculator",
	"7": "Copy and delete",
	"8": "Enter the answer",
	"9": "Directory",
	"10": "Files and folders in this directory",
	"11": "Copy files in the current directory",
	"12": "Copy specified file",
	"13": "Deleting copied fils",
	"14": "Creating a File",
	"15": "Deleting a file",
	"16": "Copy file",
	"17": "Enter the directory name",
	"18": "Current directory",
	"19": "System user",
	"20": "Operating system",
	"21": "File system Encoding",
	"22": "Press ENTER, to continue",
	"23": "Information about system",
	"24": "Reboot in progress",
	"25": "File",
	"26": "English",
	"27": "Something went wrong",
	"28": "deleted successfully!",
	"29": "Deleting copied fils",
	"30": "Python path",
	"31": "Number of deleted fils",
	"32": "Enter the name of the new file",
	"33": "Created file",
	"34": "This file was created in file_manager_11.7_stable",
	"35": "Calculator",
	"36": "Created file",
	"37": "Developer options",
	"38": "Words and phrases used in the program",
	"39": "Response",
	"40": "Created directory",
	"41": "Good-bye!",
	"42": "Enter an expression",
	"43": "ERROR: This directory already exists!",
	"44": "Specify the file name",
	"45": "Lead a sing",
	"46": "Deleted file",
	"47": "last update",
	"48": "Language",
	"49": "Copy and delete",
	"50": "Copied fils didn`t find!",
	"51": "Deleted fils",
	"52": "Deleting copied fils" ,
	"53": "Enter the directory name",
	"54": "No files that can be copy",
	"55": "Copy files",
	"56": "Create file",
	"57": 'ERROR: You specified a directory that doesn`t exist.',
	"58": "ERROR: You specified a character that can`t be counted.",
	"59": 'ERROR: You specified a nonexistent or unsupported file extension.',
	"60": 'ERROR: You tried to delete a nonexistent file.',
	"61": "Number of copied files",
	"62": "Total items",
	"63": "Number of words/phrases/sentences",
	"64": "ERROR: Division by 0 is not possible.",
	"65": "Information about the folder",
	"66": "Enter the name of the directory you want to create",
	"67": "Create directory",
	"68": "Creating directory",
	"69": "Directory",
	"70": "Create file in select directory",
	"71": "Creating file in select directory",
	"72": "Delete file",
	"73": "Deleting file",
	"74": "Additional features",
	"75": "Created fils",
	"76": "found in this directory",
	"77": "didn`t find in this directory",
	"78": "Find file",
	"79": "Finding file",
	"80": "Enter the file name",
	"81": "found in this directory.",
	"82": "didn`t find in this directory.",
	"83": "Created files",
	"84": "Number of files",
	"85": "Number of folders",
	"86": "File",
	"87": "Files",
	"88": "Folder",
	"89": "Folders",
	"90": "Didn`t find file with name",
	"91": "Coping ",
	"92": "Deleting",
	"93": "", 
	"94": "",
	"95": "",
	"96": "",
	"97": "",
	"98": "",
	"99": "",
	"100": ""
}